[package]
name = "pkauth-c"
version = "0.1.0"
authors = ["James Parker <dev@jamesparker.me>"]
# build = "build.rs"

[lib]
name = "pkauth_c"
crate-type = ["staticlib"]

[dependencies]
pkauth = {path="../rs-pkauth"}
publicsuffix = "*"
ring = "*"
staticpublicsuffix = {path="../../../Projects/staticpublicsuffix/"}

[build-dependencies]
cbindgen = "*"
